import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['artikel'] };

export const artikelOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		default: 'getAll',
		options: [
			{
				name: 'Get',
				value: 'get',
				action: 'Get an article',
				description: 'Read the master data sheet of one article',
				routing: { request: { method: 'GET', url: '/api/artikel/detail' } },
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many articles',
				description: 'List articles with the filters of the article view',
				routing: { request: { method: 'GET', url: '/api/artikel/list' } },
			},
			{
				name: 'Get Variants',
				value: 'getVariants',
				action: 'Get the variants of an article',
				description: 'List the variants actually created for a variant article',
				routing: { request: { method: 'GET', url: '/api/belege/auspraegungen' } },
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search articles',
				description: 'Type-ahead search over number, match code and description of active articles',
				routing: { request: { method: 'GET', url: '/api/belege/artikelsuche' } },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an article',
				description: 'Change master data fields. Needs the EditStammdaten permission in Sage.',
				routing: { request: { method: 'POST', url: '/api/artikel/aendern' } },
			},
		],
	},
];

export const artikelFields: INodeProperties[] = [
	{
		displayName: 'Article Number',
		name: 'artikelnummer',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...show, operation: ['get', 'getVariants'] } },
		routing: { request: { qs: { artikelnummer: '={{$value}}' } } },
	},
	{
		displayName: 'Article Number',
		name: 'artikelnummer',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { ...show, operation: ['update'] } },
		routing: { request: { body: { artikelnummer: '={{$value}}' } } },
	},
	{
		displayName: 'Query',
		name: 'q',
		type: 'string',
		required: true,
		default: '',
		description: 'Number, match code or description fragment',
		displayOptions: { show: { ...show, operation: ['search'] } },
		routing: { request: { qs: { q: '={{$value}}' } } },
	},
	{
		displayName: 'Limit',
		name: 'take',
		type: 'number',
		default: 20,
		typeOptions: { minValue: 1, maxValue: 500 },
		description: 'Max number of results to return',
		displayOptions: { show: { ...show, operation: ['search'] } },
		routing: { request: { qs: { take: '={{$value}}' } } },
	},
	{
		displayName: 'Values',
		name: 'werte',
		type: 'json',
		required: true,
		default: '{}',
		placeholder: '{ "Matchcode": "SHIRT-RED", "Gewicht": 0.35 }',
		description: 'Object of column name to value. Only fields the service exposes as editable are accepted.',
		displayOptions: { show: { ...show, operation: ['update'] } },
		routing: { request: { body: { werte: '={{ JSON.parse($value) }}' } } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { ...show, operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 500 },
		description: 'Max number of results to return',
		displayOptions: { show: { ...show, operation: ['getAll'], returnAll: [false] } },
		routing: { request: { qs: { take: '={{$value}}' } } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { ...show, operation: ['getAll'] } },
		options: [
			{
				displayName: 'Search',
				name: 'suche',
				type: 'string',
				default: '',
				routing: { request: { qs: { suche: '={{$value}}' } } },
			},
			{
				displayName: 'Custom Filter (JSON)',
				name: 'custom',
				type: 'string',
				default: '',
				description: 'JSON array of {feld, wert, bis} over the article filter catalogue',
				routing: { request: { qs: { custom: '={{$value}}' } } },
			},
			{
				displayName: 'Columns',
				name: 'spalten',
				type: 'string',
				default: '',
				description: 'Comma-separated list of columns to return',
				routing: { request: { qs: { spalten: '={{$value}}' } } },
			},
		],
	},
];
